import "./globals.css";
<<<<<<< HEAD
import { Manrope } from "next/font/google";

const manrope = Manrope({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
=======
import { Inter, Manrope } from "next/font/google";

const inter = Manrope({ subsets: ["latin"] });

export const metadata = {
  title: "Wizout",
>>>>>>> 689b3e6d3547e12c77e2483d3b091b13387e85bb
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body className={manrope.className}>{children}</body>
=======
      <body className={inter.className}>{children}</body>
>>>>>>> 689b3e6d3547e12c77e2483d3b091b13387e85bb
    </html>
  );
}
